<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .title {
            font-size: 28px;
            font-weight: bold;
            color: #0f172a;
            margin-bottom: 10px;
        }
        .subtitle {
            font-size: 16px;
            color: #64748b;
            margin-bottom: 5px;
        }
        .stats-table {
            width: 100%;
            margin-bottom: 40px;
            border-collapse: collapse;
        }
        .stats-table td {
            width: 33.33%;
            text-align: center;
            padding: 20px;
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
            display: block;
            margin-bottom: 5px;
        }
        .stat-label {
            font-size: 12px;
            text-transform: uppercase;
            color: #64748b;
            font-weight: bold;
        }
        .section-title {
            font-size: 20px;
            color: #0f172a;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 10px;
            margin-bottom: 20px;
            margin-top: 40px;
        }
        .narrative {
            font-size: 14px;
            text-align: justify;
        }
        .locations-list {
            list-style-type: none;
            padding: 0;
        }
        .locations-list li {
            padding: 10px 0;
            border-bottom: 1px solid #f1f5f9;
        }
        .loc-name {
            font-weight: bold;
            color: #334155;
        }
        .loc-count {
            float: right;
            color: #2563eb;
            font-weight: bold;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 20px;
        }
    </style>
</head>
<body>

    <div class="header">
        <div class="title">{{ $report->title }}</div>
        <div class="subtitle">Campaign: {{ $report->campaign->title }}</div>
        @if($report->report_period)
            <div class="subtitle">Period: {{ $report->report_period }}</div>
        @endif
        <div class="subtitle">Date: {{ now()->format('F j, Y') }}</div>
    </div>

    <table class="stats-table">
        <tr>
            <td>
                <span class="stat-value">{{ number_format($report->beneficiary_count) }}</span>
                <span class="stat-label">Beneficiaries Reached</span>
            </td>
            <td>
                <span class="stat-value">${{ number_format($report->funds_used, 0) }}</span>
                <span class="stat-label">Funds Utilized</span>
            </td>
            <td>
                <span class="stat-value">{{ $report->locations->count() }}</span>
                <span class="stat-label">Locations Served</span>
            </td>
        </tr>
    </table>

    <div class="section-title">Outcomes & Impact</div>
    <div class="narrative">
        {!! nl2br(e($report->outcomes_narrative)) !!}
    </div>

    @if($report->locations->count() > 0)
        <div class="section-title">Beneficiary Locations</div>
        <ul class="locations-list">
            @foreach($report->locations as $loc)
                <li>
                    <span class="loc-name">{{ $loc->name }}</span>
                    <span class="loc-count">{{ number_format($loc->beneficiaries) }} helped</span>
                    @if($loc->description)
                        <br><span style="font-size: 12px; color: #64748b;">{{ $loc->description }}</span>
                    @endif
                </li>
            @endforeach
        </ul>
    @endif

    <div class="footer">
        Generated by CharityHub &bull; {{ config('app.url') }}
    </div>

</body>
</html>
