<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Impact Report — {{ $report->title }}</title>
<style>
    body { font-family: 'DejaVu Sans', Arial, sans-serif; color: #1f2937; font-size: 11pt; }
    h1 { color: #064e3b; font-size: 22pt; margin-bottom: 4mm; }
    h2 { color: #059669; font-size: 14pt; margin: 6mm 0 3mm; border-bottom: 1px solid #d1fae5; padding-bottom: 2mm; }
    .header { background: #064e3b; color: white; padding: 8mm 10mm; margin: -8mm -10mm 8mm; }
    .header h1 { color: white; }
    .stat-grid { display: flex; gap: 6mm; margin: 4mm 0; }
    .stat-box { flex: 1; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 3mm; padding: 4mm; text-align: center; }
    .stat-value { font-size: 20pt; font-weight: bold; color: #059669; }
    .stat-label { font-size: 9pt; color: #6b7280; }
    .narrative { line-height: 1.8; color: #374151; margin: 4mm 0; }
    .location-list { margin: 4mm 0; }
    .location-item { padding: 3mm; border-bottom: 1px solid #e5e7eb; }
    .footer { margin-top: 8mm; font-size: 8pt; color: #9ca3af; text-align: center; }
    page { page-break-after: always; }
</style>
</head>
<body>
<div class="header">
    <div style="font-size: 9pt; letter-spacing: 2px; text-transform: uppercase; opacity: 0.7; margin-bottom: 2mm;">CharityHub Foundation — Impact Report</div>
    <h1>{{ $report->title }}</h1>
    <div style="font-size: 10pt; opacity: 0.8;">Campaign: {{ $campaign->title }} | Period: {{ $report->report_period ?? 'N/A' }}</div>
</div>

<h2>Key Metrics</h2>
<div class="stat-grid">
    <div class="stat-box">
        <div class="stat-value">{{ number_format($report->beneficiary_count) }}</div>
        <div class="stat-label">Beneficiaries Reached</div>
    </div>
    <div class="stat-box">
        <div class="stat-value">${{ number_format($report->funds_used, 0) }}</div>
        <div class="stat-label">Funds Utilized</div>
    </div>
    <div class="stat-box">
        <div class="stat-value">{{ $locations->count() }}</div>
        <div class="stat-label">Locations Served</div>
    </div>
</div>

<h2>Outcomes & Narrative</h2>
<div class="narrative">{{ $report->outcomes_narrative }}</div>

@if($locations->count() > 0)
<h2>Beneficiary Locations</h2>
<div class="location-list">
    @foreach($locations as $location)
    <div class="location-item">
        <strong>{{ $location->name }}</strong>
        ({{ $location->latitude }}, {{ $location->longitude }})
        — {{ number_format($location->beneficiaries) }} beneficiaries
        @if($location->description)<br><small>{{ $location->description }}</small>@endif
    </div>
    @endforeach
</div>
@endif

<div class="footer">
    Generated by CharityHub on {{ $generatedAt->format('F j, Y \a\t H:i') }}
    | Report ID: {{ $report->id }}
</div>
</body>
</html>
